components_manager:
  task_processors:
    main-task-processor:
      worker_threads: 4
    fs-task-processor:
      worker_threads: 2

  default_task_processor: main-task-processor

  components:
    server:
      listener:
        port: 8080
        task_processor: main-task-processor

    logging:
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: '@stderr'
          level: info
          overflow_behavior: discard

    dynamic-config:
      defaults:
        POSTGRES_CONNECTION_POOL_SIZE: 10

    testsuite-support: {}

    handler-ping:
      path: /ping
      method: GET
      task_processor: main-task-processor

    hotel-booking-db:
      dbconnection: $dbconnection
      blocking_task_processor: fs-task-processor
      dns_resolver: async

    mongo-hotel-booking:
      dbconnection: $mongo_uri

    storage: {}

    response-cache: {}

    rate-limiter: {}
    mongo-storage: {}

    handler-register:
      path: /auth/register
      method: POST
      task_processor: main-task-processor

    handler-login:
      path: /auth/login
      method: POST
      task_processor: main-task-processor

    handler-users:
      path: /users
      method: GET
      task_processor: main-task-processor

    handler-hotels:
      path: /hotels
      method: GET,POST
      task_processor: main-task-processor

    handler-rooms:
      path: /rooms
      method: GET
      task_processor: main-task-processor

    handler-bookings:
      path: /bookings
      method: GET,POST,DELETE
      task_processor: main-task-processor

    handler-reviews:
      path: /reviews
      method: POST
      task_processor: main-task-processor

    handler-mongo-bookings:
      path: /mongo/bookings
      method: GET,POST,DELETE
      task_processor: main-task-processor

    handler-mongo-reviews:
      path: /mongo/reviews
      method: GET,POST
      task_processor: main-task-processor
